from typing import Protocol, AsyncIterator


class AIProvider(Protocol):
    async def generate(self, prompt: str) -> str: ...
    async def stream(self, prompt: str) -> AsyncIterator[str]: ...
    def supports_vision(self) -> bool: ...
    def supports_tools(self) -> bool: ...
